# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Self service App' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Self service App
    pod 'Cartography'
    pod 'Alamofire', '~> 4.0'
    pod 'SkyFloatingLabelTextField', '~> 2.0.0'
    pod 'SwiftyJSON'
    pod 'BubbleTransition', '~> 2.0.0'
    pod 'RSBarcodes_Swift', '~> 3.0.1'
end
