# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Self service App' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Self service App
    pod 'Cartography'
    pod 'Alamofire', '~> 4.0'
    pod 'SkyFloatingLabelTextField', '~> 2.0.0'
    pod 'SwiftyJSON'
    pod 'BubbleTransition', '~> 2.0.0'
    pod 'RSBarcodes_Swift', '~> 3.0.1'
    pod 'PMAlertController'
    pod 'Eureka', '~> 2.0.0-beta.1'
    pod 'CreditCardRow', '~> 2.0'
    pod 'PostalAddressRow', '~> 1.0'
    pod 'Dollar'
    pod 'Whisper'
    pod 'TokenRow'
    pod 'KCFloatingActionButton', '~> 2.2.0'
    pod 'PMAlertController'
    pod 'SwiftMoment'
end
